version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - ./backend/tanktics/main.py:/backend/tanktics/main.py
      - ./backend/tanktics/src:/backend/tanktics/src
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/tanktics/src
    depends_on:
      - backend

volumes:
  mongodb_data:
